version: "3.8"
services:
  raspap:
    container_name: raspap
    hostname: raspap-docker
    #image: ghcr.io/raspap/raspap-docker:latest
    build: .
    privileged: true
    network_mode: host
    #cgroup: host # uncomment when using an ARM device 
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - 8081:8081
    restart: unless-stopped